### ISSUE TITLE
[BUG] Query creates unexpected behaviour and cannot be explained

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/sql#104] opened 2021-06-03 21:31 UTC
**Describe the bug**
Some queries will execute and yet cannot be explained. Query result was unexpected.

**To Reproduce**
1. Go to Query Workbench
2. Run `SHOW tables LIKE .%` (note the `.`) 
3. Click the Run button 
4. See the results (I have two less here than with `SHOW tables LIKE %` - why? 🤷‍♂️ Doesn't seem to follow the wildcard pattern)
5. Click 'Explain' 
6. The results will be "This query is not explainable."

**Expected behavior**
Any run-able query can be explained.

**Plugins**
All OpenSearch Plugins.

**Host/Environment (please complete the following information):**
 - OS: MacOs
 - Version Chrome Version 90.0.4430.212 (Official Build) (x86_64)
 - OpenSearch 1.0 RC-1

**Comment by chloe-zh** [comment] 2021-06-04 20:42
Hi Kyle @stockholmux  thanks for reporting the bug. I just reproduced this issue in my local host. For the `SHOW` statement, the (valid) system indices are by default not showing up from the query engine. I also tried out the query `show tables like '.%'` where the wildcard is quoted with single quotes since the wildcard name has special character in it, and the result gives the full list of indices starting with dot including the valid system indices. We will investigate this bug to make it behavior more properly. Thanks!

As for the explanation of queries, I tried the queries `show tables like %` and`show tables like '.%'` in devtools and workbench to test the behavior of both the engine and the workbench, looks like it's working fine:
```
POST _plugins/_sql/_explain
{
  "query": "show tables like '.%'"
}

{
  "root": {
    "name": "ProjectOperator",
    "description": {
      "fields": "[TABLE_CAT, TABLE_SCHEM, TABLE_NAME, TABLE_TYPE, REMARKS, TYPE_CAT, TYPE_SCHEM, TYPE_NAME, SELF_REFERENCING_COL_NAME, REF_GENERATION]"
    },
    "children": [
      {
        "name": "FilterOperator",
        "description": {
          "conditions": """like(TABLE_NAME, ".%")"""
        },
        "children": [
          {
            "name": "OpenSearchSystemIndexScan",
            "description": {
              "request": "OpenSearchCatIndicesRequest{}"
            },
            "children": []
          }
        ]
      }
    ]
  }
}
```
I thinks the "not runnable" issue might come from the missing single quotes.

**Comment by dai-chen** [comment] 2022-12-14 18:33
Closing. Please reopen as needed. Thanks!

**Closed by dai-chen** 2022-12-14 18:33 UTC
Labels: bug, workbench
