### ISSUE TITLE
opensearch_sql_odbc.taco cannot be found [BUG]

### ISSUE THREAD

**Issue by elliotweissberg** [opensearch-project/sql#629] opened 2022-05-26 23:39 UTC
**What is the bug?**
The connector file `opensearch_sql_odbc.taco` that is linked in the read me does not seem to exist, and leads to a page not found error.

**How can one reproduce the bug?**
1. Go to '[project home page](https://github.com/opensearch-project/sql/tree/main/sql-odbc)'
2. Click on 'Tableau connector'

**Comment by acarbonetto** [comment] 2022-05-26 23:45
Yes.  The connector links should get updated.  However, if you're looking for the latest connectors, you can download the 2.0.0 release connectors from: https://github.com/opensearch-project/sql/actions/runs/2392486854

**Comment by elliotweissberg** [comment] 2022-05-27 14:39
Thanks! I see that the `.pkg` file is also in the release notes. It would also be immensely useful if there was some kind of link to them from the readMe as well. Currently, the readMe makes reference to the driver package, but does not mention where to find them.

**Comment by elliotweissberg** [comment] 2022-05-27 17:23
@acarbonetto The 2.0.0 release connector for tableau is called `opensearch_sql_jdbc.taco`, but everything else in the docs seems to recommend using `ODBC`. Is the tableau connector misnamed, or should I be using JDBC to connect opensearch to tableau?

**Comment by acarbonetto** [comment] 2022-05-27 22:24
You shouldn't have trouble using the ODBC driver in tableau, but there was an issue creating the connector with the ODBC (I don't know exactly which existing issue is related).  So it was created with JDBC.  That's all the background that I know of.

**Comment by acarbonetto** [comment] 2022-05-27 22:24
this issue is a duplicate of https://github.com/opensearch-project/sql/issues/439

**Comment by acarbonetto** [comment] 2022-05-27 23:18
@elliotweissberg sounds like the odbc driver in tableau is giving some people issues (https://github.com/opensearch-project/sql/issues/248) and this may be an issue.  Recommend using the jdbc driver instead, at least for now.

**Comment by Yury-Fridlyand** [comment] 2022-09-12 22:28
Fixed by #665

**Closed by Yury-Fridlyand** 2022-09-12 22:28 UTC
Labels: bug, ODBC
