### ISSUE TITLE
[BUG] Fix CodeQL issue

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/sql#1168] opened 2022-12-13 20:59 UTC
**What is the bug?**
https://github.com/opensearch-project/sql/pull/1063/checks?check_run_id=10073672658

**Comment by Yury-Fridlyand** [comment] 2022-12-14 01:32
Isn't a duplicate of #889?

**Comment by joshuali925** [comment] 2022-12-14 16:54
yes it's duplicate of #889, closing. Should I dismiss the alerts? we included Grok's source code to support serialization but it's mostly an external library, we can keep the other issue for improvements on circuit breaker

**Closed by joshuali925** 2022-12-14 16:54 UTC
Labels: bug
