### ISSUE TITLE
[BUG] Build fail on main branch

### ISSUE THREAD

**Issue by seankao-az** [opensearch-project/sql#1574] opened 2023-04-24 17:25 UTC
**What is the bug?**
Build fail on main branch. OS core main branch [change Metadata members from ImmutableOpenMap to Map](https://github.com/opensearch-project/OpenSearch/pull/7165). And this makes sql fail to compileJava.

**How can one reproduce the bug?**
1. checkout to latest main branch
2. ./gradlew run

**What is the expected behavior?**
Need to be modify code in sql to adapt to the changes in OS core.

**Comment by Yury-Fridlyand** [comment] 2023-04-24 17:29
Duplicate of #1570, fixed by #1571

**Closed** 2023-04-24 17:31 UTC
Labels: bug, untriaged
