### ISSUE TITLE
Publish download link for JDBC Driver

### ISSUE THREAD

**Issue by davidcui1225** [opensearch-project/sql#335] opened 2021-12-14 18:22 UTC
Publish download link for the JDBC driver independently from ODBC

**Comment by Yury-Fridlyand** [comment] 2021-12-21 05:06
Isn't it a duplicate of #244?

**Comment by davidcui1225** [comment] 2021-12-27 17:37
Not quite, the releases for JDBC and ODBC are being tracked separately and will be released independently of each other, so I created a separate issue for JDBC since that one is on track to be released first

**Comment by joshuali925** [comment] 2022-01-24 17:47
closed by https://github.com/opensearch-project/project-website/pull/635, links are available on https://opensearch.org/artifacts

**Closed by joshuali925** 2022-01-24 17:47 UTC
Labels: enhancement
