### ISSUE TITLE
[BUG]Integ Test Failure.

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/sql#1743] opened 2023-06-15 02:20 UTC
**What is the bug?**
```
  1> [2023-06-15T08:17:02,588][INFO ][o.o.s.p.StandaloneIT     ] [testSourceFieldQuery{request_id=680cfdb5-c02e-4126-b137-9732e620ad40}] after test
  2> REPRODUCE WITH: ./gradlew ':integ-test:integTest' --tests "org.opensearch.sql.ppl.StandaloneIT.testSourceFieldQuery" -Dtests.seed=5D20B604A18492F -Dtests.security.manager=false -Dtests.locale=tr -Dtests.timezone=Asia/Kashgar -Druntime.java=11
  2> org.junit.ComparisonFailure: expected:<...,
          "type": "str[i]ng"
        }
      ],
      "da...> but was:<...,
          "type": "str[ı]ng"
        }
      ],
      "da...>
        at __randomizedtesting.SeedInfo.seed([5D20B604A18492F:9F5083E7491BC521]:0)
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.opensearch.sql.ppl.StandaloneIT.testSourceFieldQuery(StandaloneIT.java:104)
  2> NOTE: leaving temporary files on disk at: /local/home/reddyvam/opensource/sql/integ-test/build/testrun/integTest/temp/org.opensearch.sql.ppl.StandaloneIT_5D20B604A18492F-001
  2> NOTE: test params are: codec=Asserting(Lucene95): {}, docValues:{}, maxPointsInLeafNode=1249, maxMBSortInHeap=7.262518756121595, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=tr, timezone=Asia/Kashgar
  2> NOTE: Linux 5.4.242-163.349.amzn2int.x86_64 amd64/Amazon.com Inc. 11.0.19 (64-bit)/cpus=36,threads=1,free=381986968,total=536870912
  2> NOTE: All tests run in this JVM: [StandaloneIT]

Tests with failures:
 - org.opensearch.sql.ppl.StandaloneIT.testSourceFieldQuery
 ```
**How can one reproduce the bug?**
```
 ./gradlew ':integ-test:integTest' --tests "org.opensearch.sql.ppl.StandaloneIT.testSourceFieldQuery" -Dtests.seed=5D20B604A18492F -Dtests.security.manager=false -Dtests.locale=tr -Dtests.timezone=Asia/Kashgar -Druntime.java=11
 ```

**Comment by Yury-Fridlyand** [comment] 2023-06-15 02:31
Duplicate of #1590. Please, close one of copies.

**Closed** 2023-06-15 02:32 UTC
Labels: bug, v.2.9.0
