### ISSUE TITLE
[BUG] The command line tool opensearchsql does not work for ppl

### ISSUE THREAD

**Issue by neosun100** [opensearch-project/sql#768] opened 2022-08-17 14:30 UTC
**What is the bug?**
A clear and concise description of the bug.
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/13846998/185161053-ae15ae2d-fd2a-4cd1-b80f-0f9d6c1938d6.png">

**Comment by dai-chen** [comment] 2022-08-17 16:06
@neosun100 Thanks for reporting the issue! Will confirm if it supports PPL.

**Comment by dai-chen** [comment] 2022-08-18 16:40
I checked out the code and confirmed the `-p` argument does support PPL. Please provide more details so we can reproduce the issue. Thanks!

**Comment by dai-chen** [comment] 2022-08-22 22:15
@neosun100 Closing the issue for now since I don't hear back from you. Feel free to reopen as needed.

**Closed by dai-chen** 2022-08-22 22:15 UTC
Labels: bug, CLI
