### ISSUE TITLE
[BUG] fetch_size doesn't seem to work as described

### ISSUE THREAD

**Issue by peter-iron** [opensearch-project/sql#241] opened 2021-10-22 13:15 UTC
**Describe the bug**
Hitting the /_opendistro/_sql endpoint with `fetch_size` in the body does not return a `cursor` field in the response even when it should. Providing a negative value does generate an error, so it is being provided and parsed properly and simply doesn't seem to have any impact on the return.

**To Reproduce**
1. Construct a basic query that returns more than 2 results in your local instance
2. using the application/json header: `POST {"query": $query, "fetch_size": 2}`
3. Observe that you see receive the full, normal (>2 docs) response without a cursor

**Expected behavior**
I would expect to receive only 2 docs in response with a cursor entry that I could use in a subsequent `POST {"cursor": $cursor}` call to obtain more results from the same query.

**Plugins**
Please list all plugins currently enabled.

**Host/Environment (please complete the following information):**
 - OS: macOS
 - Version 11.6

**Additional context**
* [How it should work](https://opendistro.github.io/for-elasticsearch-docs/docs/sql/endpoints/#cursor)
* [Limitations](https://opendistro.github.io/for-elasticsearch-docs/docs/sql/limitation/#pagination-only-supports-basic-queries)

**Comment by dai-chen** [comment] 2022-12-12 18:11
Closing this since we're unable to reproduce. Feel free to reopen if more info you can provide. Thanks!

**Closed by dai-chen** 2022-12-12 18:11 UTC
Labels: bug, SQL
