### ISSUE TITLE
[BUG] Allowing date in format `yyyy-MM-dd HH:mm:ss.SSSSSS`

### ISSUE THREAD

**Issue by FreCap** [opensearch-project/sql#126] opened 2021-06-13 20:38 UTC
**Describe the bug**

This should succeed:

```
DELETE test_db_date_parse

PUT test_db_date_parse
{
  "mappings": {
      "properties": {
        "update": {
          "type": "date",
          "format": "strict_date_optional_time||epoch_millis||strict_date||yyyy-MM-dd HH:mm:ss||yyyy-MM-dd HH:mm:ss.SSSSSS"
        }
      
    }
  }
}

PUT test_db_date_parse/_doc/2
{

  "update":"2021-06-10 09:32:21.111974"
}

POST _opendistro/_sql
{
"query" : """SELECT * 
FROM test_db_date_parse
 """
}

```

Opendistro improvement for some use cases: https://github.com/opendistro-for-elasticsearch/sql/pull/1118

**Comment by penghuo** [comment] 2021-06-24 18:52
Thanks for reporting the issue.

**Comment by penghuo** [comment] 2021-06-24 18:54
Could you rebase the [PR](https://github.com/opendistro-for-elasticsearch/sql/pull/1118) to OpenSearch?

**Comment by FreCap** [comment] 2021-06-24 22:53
At the moment I’m still working on ES until OpenSearch is announced stable and adopted by major companies.
Reporting it because I still believe in the long term of the project

**Comment by acarbonetto** [comment] 2023-06-19 20:10
duplicate of: https://github.com/opensearch-project/sql/issues/794

**Closed** 2023-07-11 06:14 UTC
Labels: bug, v2.9.0
