### ISSUE TITLE
Publish download links for ODBC and JDBC drivers

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/sql#244] opened 2021-10-23 02:05 UTC
**Is your feature request related to a problem? Please describe.**
I tried to download ODBC driver and the [official website redirects](https://opensearch.org/docs/latest/search-plugins/sql/odbc/) me to [this repository](https://github.com/opensearch-project/sql/tree/main/sql-odbc). Actually, it contains the source code; the installation package link is still nowhere published.
The same situation with [JDBC driver](https://opensearch.org/docs/latest/search-plugins/sql/jdbc/) download link.

**Describe the solution you'd like**
The download links for JDBC and ODBC (x64 and x86) both should be published on the website and on the repo.

**Describe alternatives you've considered**
It is possible to download installer from GitHub Actions artifacts. This way is extremely unclear and not obvious. It is possible to refer it as a temporary solution only.

**Additional context**
Once a newer version of drivers would be released, the download links should be updated automatically.

**Comment by stockholmux** [comment] 2022-01-31 17:34
Closed by opensearch-project/project-website#635

ODBC/JDBC are now published 🎉

**Closed by stockholmux** 2022-01-31 17:34 UTC
Labels: enhancement

**Comment by nicotiendamia** [comment] 2022-05-26 14:42
Hello @stockholmux Kyle, could you please point me to the installation link? I've followed the build instructions and the .msi is nowhere to be found to complete the installation. Please help!!

**Comment by forestmvey** [comment] 2022-05-26 16:26
> Hello @stockholmux Kyle, could you please point me to the installation link? I've followed the build instructions and the .msi is nowhere to be found to complete the installation. Please help!!

ODBC and JDBC artifacts can be found here: [opensearch.org/artifacts](https://opensearch.org/artifacts)

**Comment by nicotiendamia** [comment] 2022-05-26 16:35
@forestmvey Kyle thanks for your response! Yeah, i actually navigated some more through the issues and found the link, i downloaded this [opensearch-sql-odbc-win64-1.4.0.0.msi](https://artifacts.opensearch.org/opensearch-clients/odbc/opensearch-sql-odbc-win64-1.4.0.0.msi).
Now am getting an issue where it says the SQL plugin could not be found and i'm not quite getting how to install it, could you help me with that?
![image](https://user-images.githubusercontent.com/89150079/170533127-e344bb2e-6477-4c4f-828f-298994583e90.png)

**Comment by forestmvey** [comment] 2022-05-26 17:11
@nicotiendamia 
What are your DSN configuration settings. Note there is currently a bug that if you need an SSL connection you need to use `https://` prefix in your host parameter. 

Related: [github_issue-280](https://github.com/opensearch-project/sql/issues/280)

**Comment by forestmvey** [comment] 2022-05-26 17:41
@nicotiendamia 
For Tableau you will need to install the `.tdc` file from the installed ODBC directory. Follow installation instructions for using tdc file in tableau here: [odbc_customize](https://help.tableau.com/current/pro/desktop/en-us/odbc_customize.htm)
With the tdc file installed you should be able to make a connection to AWS via ODBC driver by going to 
`To a Server -> More... -> Other Databases(ODBC)`
That is how to connect on mac so I would think windows would be similar.

**Comment by nicotiendamia** [comment] 2022-05-26 17:54
@forestmvey Yes i did that too, i've been with this issues since Monday, so i followed every doc i found, but still geting this issue about the SQL Plugin. WHere can i find this? Or you would say that isn't really the issue and the error message is confusing me?

**Comment by joshuali925** [comment] 2022-05-26 18:06
@nicotiendamia docs are in this directory: https://github.com/opensearch-project/sql/tree/main/sql-odbc/docs/user

ODBC driver says SQL plugin is not available if SQL plugin is not installed, or if connection is not successful (which can be confusing). Are you able to connect to your SQL endpoint using [`curl`](https://curl.se/windows/)?

e.g. `curl -k -X POST "https://user:pass@ip:port/_plugins/_sql" -H 'Content-Type: application/json' -d'{"query": "show tables like %"}'`

**Comment by nicotiendamia** [comment] 2022-05-26 19:13
@joshuali925 sorry for the late response, i've been trying different things. I'm able yes to get a response through curl, so what would be the problem? Thankss!!

**Comment by joshuali925** [comment] 2022-05-26 19:42
@nicotiendamia so issue is probably in ODBC config.

1. Are you connecting to an AWS managed endpoint or did you set up OpenSearch on your own?
2. Which version of OpenSearch?
3. How did you authenticate if any? e.g. aws credentials, username password, ..

you can also check logs from odbc driver and opensearch to see what the issue is

**Comment by nicotiendamia** [comment] 2022-05-26 19:50
@joshuali925 answering your points:

1. Indeed, i'm connecting to one of my companies endpoints in AWS
2. Checking in AWS i see 1.2 (latest)
3. I didn't authenticate. In the curl that you guys suggested i also didn't authenticate, but there i correctly got results

![Screenshot 2022-05-26 164753](https://user-images.githubusercontent.com/89150079/170566265-bbe9971d-b30e-4f42-beee-d9acf0684160.png)

**Comment by joshuali925** [comment] 2022-05-26 20:59
@nicotiendamia have you tried prefixing host with `https://` or `http://`? I tried on my side just now, it works with only `Host`: `https://xxx.com/`, do you have any special setup? logs will also help. 

And probably not likely but if you see a default profile in `<your-home-dir>/.aws/credentials`, also copy it to a new profile named `opensearchodbc`.

**Comment by joshuali925** [comment] 2022-05-26 21:38
@nicotiendamia the database not found should be ok, I also see it on a successful connection. Is your VPN globally enabled or only some softwares go through it?

https://github.com/opensearch-project/sql/blob/main/sql-odbc/src/sqlodbc/opensearch_communication.cpp#L509 this looks very general.. don't know if there's a way to see what the unknown exception is

**Comment by nicotiendamia** [comment] 2022-05-26 21:49
@joshuali925 I know, its exactly what i thought when i went through the code of that file, that the Exception im experiencing is a generic one, for how it's coded there isn't a way to see the specific exception.

The Infrastructure department told me the VPN shouldn't be a problem to use with the driver.

This is driving me crazy, i've been having issues with this driver since Monday and it's the only possibility i have to establish the connection i want :(

**Comment by MaxKsyunz** [comment] 2022-05-27 05:56
> @joshuali925 sorry for the late response, i've been trying different things. I'm able yes to get a response through curl, so what would be the problem? Thankss!!

@nicotiendamia what did you get from the server in this case?

 Could you also run `curl` with `-v` flag and confirm that the response code is 200? 
 
Since you did get a response from `curl` and the log indicates that it's in `ParseErrorResponse` function (`Parsing error response (with schema validation)` line) my theory is that it's trying to apply the `ERROR_RESPONSE_SCHEMA` to JSON with a list of tables. That fails with an exception, and `ParseErrorResponse` generates a generic `std::exception` which then gets swallowed by `CheckSQLPluginAvailability`.

**Comment by MaxKsyunz** [comment] 2022-05-27 06:15
@nicotiendamia a better option might be to use the RC version of the Tableau Connector.

You can find the connector [here](https://github.com/opensearch-project/sql/actions/runs/2204957496). [This](https://tableau.github.io/connector-plugin-sdk/docs/run-taco) page explains how to use it. The two important bits are -- putting the TACO in the correct directory and starting Tableau without signature verification.

You will need to install the JDBC driver to use it. Instructions are [here](https://help.tableau.com/current/pro/desktop/en-us/examples_otherdatabases_jdbc.htm).

I also found the `sql-jdbc` [readme](https://github.com/opensearch-project/sql/tree/main/sql-jdbc) very helpful in getting the connection string just right.

**Comment by nicotiendamia** [comment] 2022-05-27 06:54
@MaxKsyunz Thanks, will try this things out!!

**Comment by ChristineChetty11** [comment] 2022-06-09 16:12
@nicotiendamia Are you including Port number? If so, try removing that in your setup only provide the domain endpoint and also be sure to check Hostname validation in advanced settings. UI have been struggling with this for much of today and this worked for me, also make sure you use version 1.4.0 of the driver
