### ISSUE TITLE
[FEATURE] ODBC driver for Linux

### ISSUE THREAD

**Issue by adcalsie2** [opensearch-project/sql#628] opened 2022-05-26 14:35 UTC
**Is your feature request related to a problem?**
Microstrategy Business Intelligence tool installed on a Linux server. Need to get data from opensearch.

**What solution would you like?**
ODBC driver Linux version

**What alternatives have you considered?**
Any suggestion to get data from Opensearch to Microstrategy (Linux version) always be welcome

**Comment by MaxKsyunz** [comment] 2022-05-26 20:39
@adcalsie2, it looks like Microstrategy can [use](https://community.microstrategy.com/s/article/KB250923-Connecting-to-Databases-using-JDBC-Drivers-in?language=en_US) JDBC drivers.

Will the JDBC driver help you get going?

**Comment by Yury-Fridlyand** [comment] 2022-06-25 05:14
Duplicate of #461

**Comment by dai-chen** [comment] 2022-08-30 16:41
Closing as duplicated. Please track https://github.com/opensearch-project/sql/issues/461. Thanks!

**Closed by dai-chen** 2022-08-30 16:41 UTC
Labels: enhancement, ODBC
