### ISSUE TITLE
[FEATURE] BI tools compliance with complex objects

### ISSUE THREAD

**Issue by kushagraag2003** [opensearch-project/sql#3174] opened 2024-11-29 16:23 UTC
**Is your feature request related to a problem?**
Opensearch and SQL plugin use dot notation to delimit fields and subfields for nested objects. BI tools (like Power BI and Tableau,etc ) don't use DESCRIBE request to get list of columns. Instead it uses queries like select * to get list of columns
Follow up of https://github.com/opensearch-project/sql/issues/1793

**What solution would you like?**
Add new SQL plugin setting with boolean value. By default it is deactivated (unset). Once set, it will enforce expanding all complex objects in select * query.

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by anasalkouz** [comment] 2024-12-17 19:04
Seems, this this a duplicate of https://github.com/opensearch-project/sql/issues/1793. Closing this issue for now, please feel free to reopen if needed.

**Closed by anasalkouz** 2024-12-17 19:04 UTC
Labels: enhancement
